# Generated by Django 2.1.2 on 2020-03-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardlist',
            options={'managed': False},
        ),
    ]
