# Generated by Django 2.1.2 on 2020-03-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0002_auto_20200302_2345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='boardlist',
            table='board',
        ),
    ]
