# Generated by Django 2.1.2 on 2020-03-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0003_auto_20200303_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardlist',
            options={},
        ),
    ]
