# Generated by Django 2.1.2 on 2020-03-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0004_auto_20200303_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='boardlist',
            table=None,
        ),
    ]
