# Generated by Django 2.1.2 on 2020-03-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0005_auto_20200303_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='id',
            field=models.AutoField(db_column='NO', primary_key=True, serialize=False),
        ),
    ]
