# Generated by Django 2.1.2 on 2020-03-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_main', '0008_auto_20200303_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardlist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_column='DATE', null=True),
        ),
    ]
