# Generated by Django 2.2.9 on 2020-02-10 07:13

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True),
        ),
    ]
