# Generated by Django 2.2.9 on 2020-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_boardcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='upload_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
