# Generated by Django 2.2.9 on 2020-01-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schdule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=1000)),
                ('flag', models.CharField(max_length=3)),
                ('st_date', models.DateField()),
                ('ed_date', models.DateField()),
                ('st_time', models.TimeField()),
                ('ed_time', models.TimeField()),
            ],
        ),
    ]
