# Generated by Django 2.2.9 on 2020-02-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schdule',
            name='username',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
