# Generated by Django 2.2.9 on 2020-01-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('relation', models.CharField(blank=True, max_length=25)),
                ('phone_addr', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('brithday', models.DateField(blank=True)),
            ],
        ),
    ]
